[package]
name = "lgui"
version = "0.1.0"
edition = "2021"
publish = false
readme = "README.md"

[features]
default = ["renderer-gdi", "router", "store", "widgets"]
async = []
advanced-rendering = [
  "renderer-d2d",
  "renderer-gdi",
]
backend-win32 = [
  "dep:windows",
  "windows/Win32_System_ProcessStatus",
  "windows/Win32_System_Threading",
]
clipboard = [
  "backend-win32",
  "windows/Win32_System_DataExchange",
  "windows/Win32_System_Memory",
]
open-url = ["backend-win32", "windows/Win32_UI_Shell"]
diagnostics = []
diagnostics-serde = ["diagnostics", "dep:serde"]
diagnostics-timing = ["diagnostics"]
system-diagnostics = [
  "diagnostics",
  "backend-win32",
  "windows/Win32_System_SystemInformation",
]
images = [
  "backend-win32",
  "windows/Win32_Graphics_GdiPlus",
  "windows/Win32_System_Com",
  "windows/Win32_UI_Shell",
]
multi-window = ["backend-win32"]
notifications = [
  "backend-win32",
  "windows/Data_Xml_Dom",
  "windows/UI_Notifications",
  "windows/Win32_UI_Shell",
]
router = []
renderer-gdi = ["backend-win32"]
renderer-d2d = [
  "backend-win32",
  "dep:windows-numerics",
  "diagnostics",
  "images",
  "svg",
  "windows/Win32_Graphics_Direct3D",
  "windows/Win32_Graphics_Direct3D11",
  "windows/Win32_Graphics_DirectComposition",
  "windows/Win32_Graphics_Dxgi",
]
store = []
svg = [
  "images",
  "backend-win32",
  "dep:icondata",
  "dep:resvg",
  "dep:tiny-skia",
  "dep:usvg",
]
theme = []
tokio = ["async", "dep:tokio"]
tray = ["backend-win32", "windows/Win32_UI_Shell"]
widgets = ["theme"]

[dependencies]
serde = { version = "1", optional = true, features = ["derive"] }
tokio = { version = "1", optional = true, features = ["rt"] }

[target.'cfg(windows)'.dependencies]
windows-numerics = { version = "0.3.1", optional = true }
icondata = { version = "0.7.0", optional = true, default-features = false, features = ["lucide"] }
resvg = { version = "0.45", optional = true }
tiny-skia = { version = "0.11", optional = true }
usvg = { version = "0.45", optional = true }
windows = { version = "0.62.2", optional = true, features = [
  "Win32_Foundation",
  "Win32_Graphics_Direct2D",
  "Win32_Graphics_Direct2D_Common",
  "Win32_Graphics_DirectWrite",
  "Win32_Graphics_Dwm",
  "Win32_Graphics_Dxgi_Common",
  "Win32_Graphics_Gdi",
  "Win32_System_LibraryLoader",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_Input_Ime",
  "Win32_UI_HiDpi",
  "Win32_UI_WindowsAndMessaging",
] }

[[example]]
name = "counter"
required-features = ["renderer-gdi", "widgets"]
