[package]
name = "lgui-render-win32"
version = "0.2.0"
edition = "2021"
publish = ["crates-io"]
description = "GDI and Direct2D renderers for LGUI"
license.workspace = true
readme = "README.md"
repository = "https://github.com/lius-new/lgui"
homepage = "https://github.com/lius-new/lgui"
documentation = "https://docs.rs/lgui-render-win32"
keywords = ["gui", "rendering", "gdi", "direct2d"]
categories = ["gui", "rendering", "os::windows-apis"]

[features]
default = ["gdi"]
advanced-rendering = ["gdi", "d2d", "lgui-core/advanced-rendering"]
d2d = ["diagnostics", "images", "svg", "dep:windows-numerics", "lgui-core/renderer-d2d"]
diagnostics = ["lgui-core/diagnostics", "lgui-platform-win32/diagnostics"]
gdi = ["images", "lgui-core/renderer-gdi"]
images = ["dep:image", "lgui-core/images", "lgui-platform-win32/images-win32"]
multi-window = ["lgui-core/multi-window", "lgui-platform-win32/multi-window"]
svg = ["images", "dep:resvg", "dep:tiny-skia", "dep:usvg", "lgui-core/svg", "lgui-platform-win32/svg"]

[dependencies]
image = { version = "0.25", optional = true, default-features = false, features = ["gif", "jpeg", "png", "webp"] }
lgui-core = { version = "0.2.0", path = "../lgui-core", default-features = false }
lgui-platform-win32 = { version = "0.2.0", path = "../lgui-platform-win32", default-features = false, features = ["backend-win32"] }
lgui-render-api = { version = "0.2.0", path = "../lgui-render-api" }
resvg = { version = "0.45", optional = true }
tiny-skia = { version = "0.11", optional = true }
usvg = { version = "0.45", optional = true }

[dev-dependencies]
lgui-core = { version = "0.2.0", path = "../lgui-core", default-features = false, features = ["test-support"] }
lgui-render-api = { version = "0.2.0", path = "../lgui-render-api", features = ["test-support"] }

[target.'cfg(windows)'.dependencies]
windows-numerics = { version = "0.3.1", optional = true }
windows = { version = "0.62.2", features = [
  "Win32_Foundation",
  "Win32_Graphics_Direct2D",
  "Win32_Graphics_Direct2D_Common",
  "Win32_Graphics_Direct3D",
  "Win32_Graphics_Direct3D11",
  "Win32_Graphics_DirectComposition",
  "Win32_Graphics_DirectWrite",
  "Win32_Graphics_Dxgi",
  "Win32_Graphics_Dxgi_Common",
  "Win32_Graphics_Gdi",
  "Win32_System_Com",
  "Win32_System_LibraryLoader",
  "Win32_UI_WindowsAndMessaging",
] }
