[package]
name = "lgui-render-gdi"
version = "0.2.0"
edition = "2021"
publish = ["crates-io"]
description = "GDI renderer backend for LGUI"
license.workspace = true
readme = "README.md"
repository = "https://github.com/lius-new/lgui"
homepage = "https://github.com/lius-new/lgui"
documentation = "https://docs.rs/lgui-render-gdi"
keywords = ["gui", "rendering", "gdi", "win32"]
categories = ["gui", "rendering", "os::windows-apis"]

[features]
default = []
advanced-rendering = [
  "dep:lgui-render-win32-raster",
  "lgui-render-win32-raster/gdi",
  "lgui-assets/svg",
  "lgui-core/advanced-rendering",
  "lgui-platform-win32/svg",
]
diagnostics = ["dep:lgui-diagnostics", "lgui-platform-win32/diagnostics"]
multi-window = ["lgui-core/multi-window", "lgui-platform-win32/multi-window"]

[dependencies]
lgui-assets = { version = "0.2.0", path = "../lgui-assets", default-features = false, features = ["images"] }
lgui-core = { version = "0.2.0", path = "../lgui-core", default-features = false, features = ["renderer-gdi"] }
lgui-diagnostics = { version = "0.2.0", path = "../lgui-diagnostics", optional = true }
lgui-platform-win32 = { version = "0.2.0", path = "../lgui-platform-win32", default-features = false, features = ["backend-win32", "images-win32"] }
lgui-render-api = { version = "0.2.0", path = "../lgui-render-api" }
lgui-render-win32-raster = { version = "0.2.0", path = "../lgui-render-win32-raster", optional = true, default-features = false }

[dev-dependencies]
lgui-core = { version = "0.2.0", path = "../lgui-core", default-features = false, features = ["test-support"] }
lgui-render-api = { version = "0.2.0", path = "../lgui-render-api", features = ["test-support"] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = [
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_Graphics_GdiPlus",
  "Win32_UI_WindowsAndMessaging",
] }
