[package]
name = "lgui-skia-vulkan-windows-features"
version = "0.1.0"
edition = "2021"
publish = ["crates-io"]
description = "Target-specific Skia Vulkan feature bridge for lgui on Windows"
license.workspace = true
repository = "https://github.com/lius-new/lgui"
homepage = "https://github.com/lius-new/lgui"

[dependencies]
skia-safe = { version = "=0.99.0", default-features = false, features = ["d3d", "vulkan"] }
