[package]
name = "lgui-assets"
version = "0.2.0"
edition = "2021"
publish = ["crates-io"]
description = "Image, custom paint, and SVG asset runtime for LGUI"
license.workspace = true
readme = "README.md"
repository = "https://github.com/lius-new/lgui"
homepage = "https://github.com/lius-new/lgui"
documentation = "https://docs.rs/lgui-assets"
keywords = ["gui", "assets", "images", "svg"]
categories = ["gui", "multimedia::images"]

[features]
default = ["images"]
images = ["dep:image", "dep:ureq"]
backend-winit = ["images"]
persistent-cache = ["images", "lgui-core/persistent-cache"]
renderer-skia = ["images"]
svg = ["images", "dep:icondata"]
test-support = ["lgui-core/test-support"]

[dependencies]
icondata = { version = "0.7.0", optional = true, default-features = false, features = ["lucide"] }
image = { version = "0.25", optional = true, default-features = false, features = ["gif", "jpeg", "png", "webp"] }
lgui-core = { version = "0.2.0", path = "../lgui-core", default-features = false }
ureq = { version = "2.12", optional = true, default-features = true, features = ["native-certs"] }

